### ISSUE TITLE
Домашнее задание по Node

### ISSUE THREAD

**Issue by tiny-kottan** [srg-kostyrko/kottans-js2016#8]
Complete https://gist.github.com/mkozhukharenko/74c2d55ff53f67670a6a7e1f0c37f1b0

**Comment by srg-kostyrko** [comment]
https://github.com/srg-kostyrko/kottans-js2016/tree/master/week07/lec1

**Comment by mkozhukharenko** [comment]
looks good. 

you can pass a `callback` to a `listen()` method https://github.com/srg-kostyrko/kottans-js2016/blob/master/week07/lec1/app.js#L17-L18

read more here https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback
